services:
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE:-aula}
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-asdf1234}
        ports:
            - '127.0.0.1:${MYSQL_PORT:-3306}:3306'
        volumes:
            - mysql:/var/lib/mysql
    apache:
        image: pswerlang/php-apache
        restart: unless-stopped
        ports:
            - '${APACHE_PORT:-80}:80'
        volumes:
            - ./public:/var/www/html
volumes:
    mysql: