version: '3'
services:
    mysql:
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        env_file:
            - .env
        ports:
            - '127.0.0.1:3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql
    apache:
        image: pswerlang/php-apache
        restart: always
        ports:
            - '80:80'
        volumes:
            - ./app:/var/www/html
volumes:
    mysql-data: