version: '3'
services:
    mysql:
        env_file:
            - .env
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=aula
            - MYSQL_ROOT_PASSWORD=asdf1234
        ports:
            - '127.0.0.1:3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql
    apache:
        image: pswerlang/php-apache
        restart: always
        ports:
            - '80:80'
        volumes:
            - ./app:/var/www/html
volumes:
    mysql-data: